### ISSUE TITLE
C/C++ 中#include<stdio>的显示问题

### ISSUE THREAD

**Issue by corvofeng** [zhangjikai/online-markdown-reader#1]
在我使用过程中, 当我解析的文件为C++且有include<>时,  <>符号会被省略, 经过我检查之后, 发现是代码中未对代码中的<>进行转义, 导致<stdio.h>被识别为标签
 
![screenshot from 2017-06-15 19-52-43](https://user-images.githubusercontent.com/12025071/27180285-5d13a14e-5205-11e7-80e7-010184084675.png)

 我自己做了简单探索, 并且发现在`/dist/js/index.js b/dist/js/index.js`中添加转义即可, 下面
是我的patch代码.

  可以注意到在152行处进行了简单修改. 但是由于我对程序整体没有把握, 可能并不是最合适的位置,
 所以, 提一个issue, 希望作者能够在合适的位置进行修改.

```code
diff --git a/dist/js/index.js b/dist/js/index.js
index 8af1488..8273d0f 100644
--- a/dist/js/index.js
+++ b/dist/js/index.js
@@ -152,7 +152,8 @@
                 }
                 return originalCodeFun.call(this, code, language);
             default :
-                return originalCodeFun.call(this, code, language);
+                var src = code.replace(/</g, "&lt").replace(/>/g, "&gt");
+                return originalCodeFun.call(this, src, language);
         }
     };
 ```

下图为我修改过程序之后的结果.

![screenshot from 2017-06-15 19-52-57](https://user-images.githubusercontent.com/12025071/27180419-00858fea-5206-11e7-8734-6b050ce893d3.png)

再次感谢作者的辛勤付出, 才能带来如此优秀的程序.

**Comment by TheaaaShen** [comment]
十分感谢，最近有点忙，过两天我就合进去

**Comment by zhangjikai** [comment]
十分感谢，最近有点忙，过两天就把代码合进去

**Comment by zhangjikai** [comment]
已修改
