### ISSUE TITLE
ECharts问题

### ISSUE THREAD

**Issue by UlionTse** [zhangjikai/online-markdown-reader#2]
1. Echarts地图图形显示不出，其他图形显示正常，自行加入china.js刷新后也能正常显示；
2. markdown导出为html后，html上的ECharts图形不显示（重点）。

**Comment by zhangjikai** [comment]
能给我一份你的 Markdown 文件么？

**Comment by UlionTse** [comment]
1. Markdown除ECharts部分是显示正常的，编辑器用的是`MarkdownPad2`。
2. ECharts地图示例引用链接： [http://gallery.echartsjs.com/editor.html?c=map-china-dataRange](http://gallery.echartsjs.com/editor.html?c=map-china-dataRange)

**Comment by zhangjikai** [comment]
这个是因为在 china.js 中做了一些初始化操作，导出 html 后，你可以在导出文件里手动加上 china.js，这样应该就可以正常显示了
```
<script src="http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js"></script>
<script src="http://gallery.echartsjs.com/dep/echarts/map/js/china.js"></script>
```

**Comment by UlionTse** [comment]
非常感谢。之前我也尝试了添加china.js，只不过放到了body最后面（因为你的自动生成的html引用ECharts的官方js在那儿。。。），这次放到head就对了，再次感谢。
